### ISSUE TITLE
how do i go about exporting data?

### ISSUE THREAD

**Issue by mafrahim** [zloeber/ASTExplorer#1]
I was thinking of automating and exporting the results for series of files to Json, i see that there is convertto-json in ps2+, any idea how do i go about using that to export all the generated data from script. 
Thanks.

**Comment by zloeber** [comment]
What kind of results are you looking for in your export? AST objects can get quite deep and may not lend themselves to being serialized via json easily.

**Comment by mafrahim** [comment]
hey thanks for reply, im looking to do machine learning approach to get insight of the powershell scripts, i dont know what the features would be at the moment but i need to find a way to obtain a uniformed data format for each .ps1 files and AST seems to be a very good start. it does not matter how deep the trees would be, in fact the more the better. basically a merge of treeview and listview even in xml format would be fine and i can work it.

**Comment by zloeber** [comment]
export-clixml would be your friend then. The xml created with it is horrible but it is technically xml and should contain a good deal of the object data.

**Comment by mafrahim** [comment]
yes tried it...it created 50mb xml file from 2 kb ps1 file..thanks though.

**Comment by zloeber** [comment]
Well that is the nature of AST (especially combined with .NET). I'm interested in the premise of your project but without some constraints around what data you want serialized from AST I'm not sure how you would get the input you are looking for.

**Comment by zloeber** [comment]
Haven't looked too much into the code yet but [this project ](https://github.com/lzybkr/ShowPSAst/blob/master/README.md)may be useful for you as well.
